ldcm:
  model: models.diffusion.ldcm.LDCM
  timestep: 1000
  beta_schedule: "linear"
  loss_type: "l2"
  ckpt_path: ""
  load_only_unet: False
  monitor: "val/loss"
  use_ema: True
  first_stage_key: "image"
  image_size: 256
  channels: 1
  log_every_t: 100
  clip_denoised: True
  linear_start: 1e-4
  linear_end: 2e-2,
  cosine_s: 8e-3
  given_betas: None
  original_elbo_weight: 0.0
  v_posterior: 0.0
  l_simple_weight: 1.0
  conditioniing_key: None
  parameterization: "eps"
  schedular_config: None
  use_positional_encodings: False
  learn_logvar: False
  lofvar_init: 0.0

  compress:
    model: models.vae.compress.MeanScaleHyperprior


  unet:
