module:
  target: main.Wrapper
  params:
    learning_rate: 1e-4
    aux_learning_rate: 1e-4
    compression:
      target: models.vae.compress.MeanScaleHyperprior
      params:
        ch: 1
        N: 128
        M: 192

    criterion:
      target: main.RateDistortionLoss
      params:
        lmbda: 1e-2

data:
  target: modules.dataset.util.DataModuleFromConfig
  params:
    batch_size: 1
    wrap: True
    train:
      target: modules.dataset.hologram.HologramDataset
      params:
        path: './data/train/'
        file_format: '*.png'
        size: 512
    test:
      target: modules.dataset.hologram.HologramDataset
      params:
        path: './data/test/'
        file_format: '*.png'
        size: 512

lightning:
  callbacks:
    image_logger:
      target: modules.log.logger.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2



