diffusion:
  module: models.diffusion.ldcm.LDCM
  base_learning_rate: 2.0e-6
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    #first_stage_key: image
    image_size: 64
    channels: 3
    monitor: val/loss_simple_ema

data:
  train:
    module: modules.dataset.hologram.HologramDataset
    path: './data/train/'
    file_format: '*.png'

  test:
    module: modules.dataset.hologram.HologramDataset
    path: './data/test/'
    file_format: '*.png'

compress:
  module: models.vae.compress.MeanScaleHyperprior
  channel: 1
  N: 128
  M: 256

unet:
  module: utils.CUNet.CUNet
  image_size: 256
  in_channels: 3
  out_channels: 3
  model_channels: 224
  attention_resolution:
  - 8
  - 4
  - 2
  num_res_block: 2
  channel_mult:
  - 1
  - 2
  - 3
  - 4
  num_head_channels: 32




