model:
  base_learning_rate: 4.5e-6
  target: models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 3
    lossconfig:
      target: modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 3
      resolution: 512
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0

data:
  target: modules.dataset.util.DataModuleFromConfig
  params:
    batch_size: 12
    wrap: True
    train:
      target: modules.dataset.hologram.HologramDataset
      params:
        path: './data/train/'
        file_format: '*.png'
        size: 512
    test:
      target: modules.dataset.hologram.HologramDataset
      params:
        path: './data/test/'
        file_format: '*.png'
        size: 512
    validation:
      target: modules.dataset.hologram.HologramDataset
      params:
        path: './data/validation/'
        file_format: '*.png'
        size: 512

lightning:
  callbacks:
    image_logger:
      target: modules.log.logger.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2



